# How to use GitHub Action environment variables
name: How to use GitHub Action environment variables

on:
  workflow_dispatch:

jobs:
  print_env:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables
        run: |
          echo "GITHUB_ACTION_PATH: $GITHUB_ACTION_PATH"
          echo "GITHUB_ACTION_REPOSITORY: $GITHUB_ACTION_REPOSITORY"
          echo "GITHUB_ACTION_RUN_ID: $GITHUB_ACTION_RUN_ID"
      - name: Cypress run
        run: |
          echo "FOO_BAR: $FOO_BAR"
        env:
          FOO_BAR: ${{ vars.FOO_BAR }}
