name: GitHub Action path

on:
  workflow_dispatch:

jobs:
  print_github_action_path:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print github action path
        run: |
          set -ex
          echo "Current working directory:"
          pwd

          echo "GITHUB_ACTION_PATH environment variable:"
          echo "$GITHUB_ACTION_PATH"

          echo "github.action_path context variable:"
          echo "${{ github.action_path }}"

          echo "Repository root directory contents:"
          ls -la
