name: GitHub Action path

on:
  workflow_dispatch:

jobs:
  print_github_action_path:
    runs-on: ubuntu-latest
    steps:
      - name: Print current working directory
        run: |
          set -ex
          echo "Current working directory:"
          pwd

          echo "GitHub Workspace:"
          echo "$GITHUB_WORKSPACE"

      - name: Incorrect way to print github action path
        run: |
          set -ex

          echo "GITHUB_ACTION_PATH var is empty:"
          echo "$GITHUB_ACTION_PATH"

          echo "github.action_path context variable is empty:"
          echo "${{ github.action_path }}"

          echo "FOO_GITHUB_ACTION_PATH_BAR is empty:"
          echo "$FOO_GITHUB_ACTION_PATH_BAR"
        env:
          FOO_GITHUB_ACTION_PATH_BAR: ${{ github.action_path }}
