name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GRAFANA_PASSWORD: ${{ secrets.GRAFANA_PASSWORD }}
  GRAFANA_USERNAME: ${{ secrets.GRAFANA_USERNAME }}

jobs:
  build:
    name: nodejs__grafana_loki__send_log
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install NPM packages
        run: |
          cd nodejs/grafana_loki
          npm install

      - name: Send log to Grafana Cloud
        run: |
          cd nodejs/grafana_loki
          node send_log.js
