name: Print stdout and stderr to GITHUB_STEP_SUMMARY

on:
  workflow_dispatch:

jobs:
  print_stderr_to_summary:
    runs-on: ubuntu-latest
    steps:
      - name: Create main.js
        run: |
          echo "console.log('log');" > main.js
          echo "console.error('error');" >> main.js

      # Summary panel: error
      # Log: log
      - name: Print "error" to Summary panel, but leave "log" in the Log panel
        run: node main.js 2> "$GITHUB_STEP_SUMMARY"

      - run: echo "====================" >> "$GITHUB_STEP_SUMMARY"

      # Summary panel: log
      # Log: error
      - name: Print "log" to Summary panel, but leave "error" in the Log panel
        run: node main.js 1>> "$GITHUB_STEP_SUMMARY"

      - run: echo "====================" >> "$GITHUB_STEP_SUMMARY"

      # Summary panel: log
      # Log: error
      - name: Print "log" to Summary panel, but leave "error" in the Log panel (same as above)
        run: node main.js >> "$GITHUB_STEP_SUMMARY"

      - run: echo "====================" >> "$GITHUB_STEP_SUMMARY"

      # Summary panel: error
      # Log panel: log+error
      - name: Print "error" to Summary panel, and print both "log" and "error" to the Log panel
        run: node main.js 2> >(tee -a "$GITHUB_STEP_SUMMARY")
