name: Print params

on:
  workflow_dispatch:

env:
  XX_FOO: 'BAR'
  XX_BAR: 'BAZ'

jobs:
  print_params:
    runs-on: ubuntu-latest
    steps:
      - name: Display parameters
        shell: bash
        run: echo "${{ format('<h1>Parameters</h1><p>{0}</p>', env.XX_FOO) }}" > "$GITHUB_STEP_SUMMARY"
      - name: Display complex parameters
        shell: bash
        run: |
          FORMATTED_OUTPUT=$(echo "${{ format('<h1>Parameters</h1><ul><li>{0}</li><li>{1}</li></ul>', env.XX_FOO, env.XX_BAR) }}")
          echo "$FORMATTED_OUTPUT" > "$GITHUB_STEP_SUMMARY"
