name: Print params

on:
  workflow_dispatch:

env:
  XX_FOO: 'BAR'

jobs:
  print_params:
    runs-on: ubuntu-latest
    steps:
      - name: Display parameters
        shell: bash
        run: echo "${{ format('<h1>Parameters</h1><p>{0}</p>', env.XX_FOO) }}" > "$GITHUB_STEP_SUMMARY"
      - name: Display complex parameters
        shell: bash
        run: |
          PARAM1="Value1"
          PARAM2="Value2"
          PARAM3="Value3"
          FORMATTED_OUTPUT=$(echo "${{ format('<h1>Parameters</h1><ul><li>{0}</li><li>{1}</li><li>{2}</li><li>{3}</li></ul>', env.XX_FOO, PARAM1, PARAM2, PARAM3) }}")
          echo "$FORMATTED_OUTPUT" > "$GITHUB_STEP_SUMMARY"
