name: Print console.log, console.warn, and console.error

on:
  workflow_dispatch:

jobs:
  print_console:
    runs-on: ubuntu-latest
    steps:
      - name: Create main.js
        run: |
          echo "console.log('log');" > main.js
          echo "console.log('error');" >> main.js
          echo "console.log('[error]');" >> main.js
          echo "console.log('[ERROR]');" >> main.js
          echo "console.log('[WARN]');" >> main.js
          echo "console.warn('log');" > main.js
          echo "console.warn('error');" >> main.js
          echo "console.warn('[error]');" >> main.js
          echo "console.warn('[ERROR]');" >> main.js
          echo "console.warn('[WARN]');" >> main.js
          echo "console.error('log');" >> main.js
          echo "console.error('error');" >> main.js
          echo "console.error('[error]');" >> main.js
          echo "console.error('[ERROR]');" >> main.js
          echo "console.error('[WARN]');" >> main.js

      - name: Print console.log
        run: |
          node main.js
